name: CI garagephp

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3' #ici la version de php que l'on utilise
          extensions: pdo_mysql, mbstring #ici on ajoute les extensions nécessaire
          tools: composer #installe composer

      - name: Installation des dépendances Composer
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Execution des tests PHPUnit
        run: vendor/bin/phpunit #Assurez-vous que PHPUnit est configuré